Repository stolostron/image-builder, pull requests merged in 2021-02, with the labels that each got.

#46 add docker-cli to images
  Dockerfile.go1.13-linux-amd64
  Dockerfile.go1.14-linux-amd64
  Dockerfile.go1.15-linux-amd64
  Dockerfile.nodejs10-linux-amd64
  Dockerfile.nodejs12-linux-amd64
  Dockerfile.nodejs14-linux-amd64
  build/setup-base.sh
  build/setup-docker-cli.sh
Labels: approved

#47 Update .trigger-openshift-ci
  .trigger-openshift-ci
Labels: approved, dco-signoff: no

#48 sonar: add SONAR_USER_HOME
  Dockerfile.go1.13-linux-amd64
  Dockerfile.go1.14-linux-amd64
  Dockerfile.go1.15-linux-amd64
  Dockerfile.nodejs10-linux-amd64
  Dockerfile.nodejs12-linux-amd64
  Dockerfile.nodejs14-linux-amd64
  build/setup-sonar.sh
Labels: approved

#49 Update .trigger-openshift-ci
  .trigger-openshift-ci
Labels: approved

#50 Update .trigger-openshift-ci
  .trigger-openshift-ci
Labels: approved

#51 Update .trigger-openshift-ci
  .trigger-openshift-ci
Labels: approved

#52 Update .trigger-openshift-ci
  .trigger-openshift-ci
Labels: approved

#53 Update .trigger-openshift-ci
  .trigger-openshift-ci
Labels: approved

#54 Update .trigger-openshift-ci
  .trigger-openshift-ci
Labels: approved

#55 Update .trigger-openshift-ci
  .trigger-openshift-ci
Labels: approved

#56 Update .trigger-openshift-ci
  .trigger-openshift-ci
Labels: approved

#57 Update .trigger-openshift-ci
  .trigger-openshift-ci
Labels: approved

#58 Update setup-build-harness.sh
  build/setup-build-harness.sh
Labels: approved

#59 Add yarn to nodejs builders
  .gitignore
  Dockerfile.nodejs10-linux-amd64
  Dockerfile.nodejs12-linux-amd64
  Dockerfile.nodejs14-linux-amd64
  build/setup-node.sh
  build/setup-yarn.sh
  yarn-source/package-lock.json
  yarn-source/package.json
Labels: approved

#62 go: add Go 1.16 Dockerfile
  Dockerfile.go1.16-linux-amd64
Labels: approved

#63 Update .trigger-openshift-ci
  .trigger-openshift-ci
Labels: approved

#64 go: use default GOPROXY and GOSUMDB
  Dockerfile.go1.13-linux-amd64
  Dockerfile.go1.14-linux-amd64
  Dockerfile.go1.15-linux-amd64
  Dockerfile.go1.16-linux-amd64
Labels: approved

#65 Update .trigger-openshift-ci
  .trigger-openshift-ci
Labels: approved, lgtm
